#Top page
title: My Portfolio
description: Third year project showcase
url: "https://eihunnia.github.io"               #url: "" 
baseurl: "/Project-Portfolio"                   #baseurl: "" 

# User settings
username: Emmanuel Ihunnia
user_description: Test phase of my portfolio describing my third year project
user_title: Software Developer
email: emmanuelihunnia@outlook.com
twitter_username:
github_username:
gplus_username:

# Google-analytics
google-analytics:
 id: ""

exclude: ['package.json', 'src', 'node_modules']

url: "https://USERNAME.github.io"
baseurl: "/Project-Portfolio"
