#Top page
title: My Portfolio
description: Third year project showcase
url: "https://eihunnia.github.io"               #url: "" 
baseurl: "/Project-Portfolio"                   #baseurl: "" 

# User settings
username: Emmanuel Ihunnia
user_description: Throughout my degree in Computer Science, I have gained experience coding in several languages including C, Java, Python and others which have provided me a wide base to develop software in different environments. 
I have developed a particular proficiency in Python especially during my third-year project as the entire game was designed using this language.
user_title: Software Developer
email: emmanuelihunnia@outlook.com
twitter_username:
github_username:
gplus_username:

# Google-analytics
google-analytics:
 id: ""

exclude: ['package.json', 'src', 'node_modules']

url: "https://USERNAME.github.io"
baseurl: "/Project-Portfolio"
