#Top page
title: My Portfolio
description: Third year project showcase
url: ""        
baseurl: "" 

#Pixyll theme
remote_theme: poole/hyde

#plugins
plugins: 
  - jekyll-remote-theme

# Build settings
markdown: kramdown
highlighter: rouge

# Optional Pixyll customisations
header_text: "Welcome to My Project Portfolio"
header_image: ""     # You can add a header image later
