#Top page
title: My Portfolio
url: ""        
baseurl: "" 

#Pixyll theme
remote_theme: johno/pixyll

description: Third year project showcase

# Build settings
markdown: kramdown
highlighter: rouge

# Optional Pixyll customisations
header_text: "Welcome to My Project Portfolio"
header_image: ""     # You can add a header image later
